version: "3"

services:
  mongo:
    container_name: proxectos-db
    image: mongo:4.0
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=abc123.
      - MONGODB_DATABASE=ProxectOS
    volumes:
      - proxectos-db:/data/db
volumes:
  proxectos-db:
    external: false
