version: "3"

services:
  mongo:
    container_name: proxectos-db-test
    image: mongo:4.0
    restart: always
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=abc123.
      - MONGODB_DATABASE=ProxectOS-test
    volumes:
      - proxectos-db-test:/data/db
volumes:
  proxectos-db-test:
    external: false
